### ISSUE TITLE
🐛 [Bug]:使用alpha版本的tiny-engine-cli创建平台运行报错

### ISSUE THREAD

**Issue by Nibblerrr** [opentiny/tiny-engine#897]
### Environment

edge 130.0.2849.68 (正式版本) (64 位)

### Version

node: 18.20.4

### Version

@opentiny/tiny-engine@2.0.0-rc.1

### Link to minimal reproduction

![image](https://github.com/user-attachments/assets/d815eda4-1cad-4b1c-9222-604e5d19515b)

### Step to reproduce

npx @opentiny/tiny-engine-cli@alpha create

安装依赖
pnpm i  

启动项目
pnpm dev  

启动后打开页面为空白，控制台报错
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'get')
    at ULt (index.js:6672:25)
    at init (index.js:6712:9)
    at index.js:12677:7
    at Array.forEach (<anonymous>)
    at SO (index.js:12673:61)
    at Object.beforeAppCreate (init.js:49:18)
    at gQi (init.js:137:21)
    at main.js:20:1

### What is your project name

无

**Comment by mysticdcat** [comment]
请问你现在可以了吗  我现在试了下还是报错

**Comment by chilingling** [comment]
请使用 `npx @opentiny/tiny-engine-cli create` 进行创建二开工程。

relative issue: #952

**Comment by chilingling** [comment]
> 请使用 `npx @opentiny/tiny-engine-cli create` 进行创建二开工程。
> 
> relative issue: [#952](https://github.com/opentiny/tiny-engine/issues/952)

@mysticdcat  @Nibblerrr  请使用上述方式进行创建二开工程，如果仍然遇到问题，欢迎再次打开 issue。
