### ISSUE TITLE
npm i 报错

### ISSUE THREAD

**Issue by Plortinus** [opentiny/tiny-engine#9]
```
npm ERR! code 1
npm ERR! path /Users/admin/tiny-engine/src/i18n/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:857
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR!
npm ERR! Error: Command failed: /Users/admin/tiny-engine/src/i18n/node_modules/esbuild/bin/esbuild --version
npm ERR!     at checkExecSyncError (node:child_process:861:11)
npm ERR!     at Object.execFileSync (node:child_process:896:15)
npm ERR!     at validateBinaryVersion (/Users/admin/tiny-engine/src/i18n/node_modules/esbuild/install.js:89:32)
npm ERR!     at /Users/admin/tiny-engine/src/i18n/node_modules/esbuild/install.js:242:5 {
npm ERR!   status: null,
npm ERR!   signal: 'SIGKILL',
npm ERR!   output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
npm ERR!   pid: 94608,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(0) [Uint8Array] []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2023-09-27T01_12_43_237Z-debug-0.log
```
node版本v16.20.2

**Comment by wenmine** [comment]
@Plortinus hi，试试删除node_modules和package-lock.json，清理一下npm缓存，再重新执行npm install ?

**Comment by Plortinus** [comment]
我是第一次下载,第一次安装,没有node_moduels也没有package-lock.json
